### ISSUE TITLE
xfce does not start

### ISSUE THREAD

**Issue by mcred** [alvarop/osxMojo#2]
Following the instructions and after I enter the vagrant:vagrant credentials, xfce does not start. How can I fix this?

<img width="1130" alt="screen shot 2018-09-03 at 1 47 26 pm" src="https://user-images.githubusercontent.com/4326032/44997980-105cec00-af80-11e8-9bf2-b9586fef1274.png">

**Comment by nsknyc** [comment]
mcred can you check the boot up logs?

**Comment by mcred** [comment]
@nsknyc Thanks for the reply. I moved this project over to a dedicated linux box. It's no longer an issue for me.
